"""add profile resume docx storage

Revision ID: db8f06ac41ed
Revises: e50a14e36688
Create Date: 2026-09-08 23:50:19.160477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'db8f06ac41ed'
down_revision: Union[str, Sequence[str], None] = 'e50a14e36688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('resume_docx', sa.LargeBinary(), nullable=True))
    op.add_column('profiles', sa.Column('resume_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'resume_filename')
    op.drop_column('profiles', 'resume_docx')
    # ### end Alembic commands ###
