"""unique application match id

Revision ID: e50a14e36688
Revises: 5af74a5045fa
Create Date: 2026-09-08 23:36:02.474903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e50a14e36688'
down_revision: Union[str, Sequence[str], None] = '5af74a5045fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_match', 'applications', ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_application_match', 'applications', type_='unique')
    # ### end Alembic commands ###
